//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarterSystem.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomEntities : DbContext
    {
        public DiplomEntities()
            : base("name=DiplomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Chat> Chat { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<ImageProduct> ImageProduct { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<ProductOrService> ProductOrService { get; set; }
        public DbSet<ProductTag> ProductTag { get; set; }
        public DbSet<Review> Review { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tag> Tag { get; set; }
        public DbSet<Trade> Trade { get; set; }
        public DbSet<User> User { get; set; }
    }
}
